spring:
  application:
    version: 1.0.0-dev

server:
  address: 0.0.0.0 # Network address to which the server should bind to.  
  port: 8080 # Server HTTP port.

uapollo:
  application:
    meta:
      reload:
        try-lock-time: 3 # seconds
        task:
          cron-expression: 6 6 6 * * ? #定时检查频率
    release:
      thread-nums: 2 # rlease配置线程数量
  task:
    scheduler:
      pool-size: 10 # ThreadPoolTaskScheduler pool size 
  template:
    configuration:    
      location: ${spring.property.path}/template/configuration #应用默认配置文件模板存储位置