version: '2'
services:
    uapollo-app:
        image: uapollo
        environment:
            - SPRING_PROFILES_ACTIVE=prod,swagger
            - SPRING_DATASOURCE_URL=jdbc:mysql://uapollo-mysql:3306/uapollo?useUnicode=true&characterEncoding=utf8&useSSL=false
            - JHIPSTER_SLEEP=10 # gives time for the database to boot before the application
        ports:
            - 8080:8080
    uapollo-mysql:
        extends:
            file: mysql.yml
            service: uapollo-mysql
